#' Matches groups by using numeric variables
#'
#' Matches groups by using numeric variables
#'
#' @param df data frame of numeric inputs. First column has group names, 1 line per group.
#' @param n size of the test group, and matching control group.
#' @return Outputs a list of test groups with matching control groups, 1 to 1 match.
#' @export





##----PART #1---------------------------------------------------------

# CREATE A RANKED LIST OF MATCHES BASED ON DISTANCE.

# Libraries loaded in BUILD_METRICS.R script
#require(reshape2)
#require(tidyverse)
#require(random)


match_numeric <- function ( df, n = 10 ) {

    # Prep for Distance: Convert column #1 to rownames and scale the dataset

    rownames(df) <- df[,1]
    df_scaled <- scale(df[,-1])

    #---- Build the Distant Matrix----
    DF_DIST <- dist(df_scaled , method = "euclidian")

    # Convert to Matrix
    DF_RANK_BASE <- as.matrix(DF_DIST)

    # Force NA on upper triangle and diagnol of 0's
    DF_RANK_BASE[upper.tri(DF_RANK_BASE)] <- NA
    diag(DF_RANK_BASE) <- NA

    #----Produce list of one to one distance Metric----
    DF_RANK_BASE_1 <- reshape2::melt(DF_RANK_BASE)
    names(DF_RANK_BASE_1) <- c("CONTROL","TEST","DIST_Q")

    DF_DIST_FINAL <- DF_RANK_BASE_1 %>% na.omit() %>%
      dplyr::arrange(TEST,DIST_Q,CONTROL)


    ##----PART #2----------------------------------------------------------

    # RANDOMLY SELECT THE LIST/DF OF THE TEST AND CONTROL GROUPS

    # Select random number for seed from random.org

    rand_num <- random::randomNumbers(n = 1, min = 1, max = 1000000000, 1)
    set.seed( rand_num ) # Number Generated by Random.org
    set.seed(17)
    DF_TEST <- df %>% sample_n(size = n) # Need to include a InputSelector, sample size of test

    # Test and Control List

    CONTROL_STR_LIST <- DF_DIST_FINAL %>% dplyr::filter(!CONTROL %in% (DF_TEST[,1])) %>%
      dplyr::filter(TEST %in% (DF_TEST[,1])) %>%
      dplyr::group_by(TEST) %>%
      dplyr::mutate(DIST_RANK = min_rank(DIST_Q)) %>%
      dplyr::filter(DIST_RANK <= 5) %>%
      dplyr::select(-DIST_RANK) %>%
      dplyr::ungroup() %>%
      dplyr::mutate(GROUP = row_number())

    return(CONTROL_STR_LIST)
      # assign( CONTROL_STR_LIST, paste0("Randomized Selection_seed_",rand_num), envir = .GlobalEnv #)
  }
